### ISSUE TITLE
Notebook to generate haiku

### ISSUE THREAD

**Issue by 7flash** [davanstrien/haiku-dpo#3]
Currently, a first published notebook shows how to generate prompts dataset. Please, publish second notebook which will demonstrate how to use that dataset to actually generate haiku. Thank you! @davanstrien

**Comment by davanstrien** [comment]
Hopefully, I will get the rest of the notebooks wrapped up and shared tomorrow!

**Comment by davanstrien** [comment]
All the notebooks for producing the DPO dataset are now on the repo: https://github.com/davanstrien/haiku-dpo#-notebooks. Happy to get any feedback!

**Comment by 7flash** [comment]
> All the notebooks for producing the DPO dataset are now on the repo: https://github.com/davanstrien/haiku-dpo#-notebooks. Happy to get any feedback!

Thank you! How about training model?

**Comment by 7flash** [comment]
I have found this one https://huggingface.co/davanstrien/HaikuHermes-0.1-7B

Would be amazing to see how it was trained exactly

**Comment by 7flash** [comment]
Unfortunately it fails to run @davanstrien 

```
python -m vllm.entrypoints.openai.api_server --model davanstrien/HaikuHermes-0.1-7B --max-model-len 2048 --gpu-memory-utilization 0.9 --tensor-parallel-size 1
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 6, in <module>
    from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 9, in <module>
    from vllm.utils import get_cpu_memory, is_hip
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 11, in <module>
    from vllm._C import cuda_utils
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```
